### PR TITLE
Fix hash link problem

### LINKED ISSUE #78: Website doesn't scroll to hash '#' in URL path, if present
For example, the CONTRIBUTING.md links to contributing section of manual.md
* Source: https://github.com/denoland/deno/blob/master/CONTRIBUTING.md
* Link: https://deno.land/std/manual.md#contributing

When website loads https://deno.land/std/manual.md#contributing, it doesn't scroll to the contributing section

### PR DESCRIPTION
**Pull request by ry**
Fixes #78

### CODE REVIEW

File: src/Link.tsx [hunk 1]
```diff
@@ -1,65 +1,13 @@
...
-
 interface Props extends LinkProps {
   /** Supports internal and external links */
   to: string;
 }
 
 /** Use this component instead of MaterialUI's Link or ReactRouter's Link. */
 export default function Link(props: Props) {
-  if (isInternalLink(props.to)) {
-    return <MaterialLink component={InternalLink} {...props} />;
```
Comment (lucacasonato) [inline src/Link.tsx]: The internal links should still use a React router Link component. Otherwise a full page reload happens on every navigation.
