### PR TITLE
Fixed README preview for GitHub module subdirectories

### LINKED ISSUE #245: Wrong readme is displayed for subdirectories
The wrong readme is displayed under the directory view of subdirectories (e.g. https://deno.land/std/examples/)

### PR DESCRIPTION
**Pull request by lucacasonato**
Fixes #245

### CODE REVIEW

File: src/page/Registry.js [hunk 1]
```diff
@@ -217,7 +217,7 @@ async function renderDir(pathname, entry) {
       const rawUrl =
         entryType === "esm"
           ? `${entry.url}${path}README.md`
-          : `${entry.url}README.md`;
+          : `https://raw.githubusercontent.com/${owner}/${repo}/${entry.branch}/${path}README.md`;
```
Comment (ry) [inline src/page/Registry.js]: What about non-github entries?

Comment (lucacasonato) [reply src/page/Registry.js]: This is already in a `if (entryType === "github" || entryType === "esm")` block (line 176) so it must be `github` because its not `esm`.
